---
- name: Install, update, remove Doker containers 
  hosts: Metagen19VM-32 Metagen19VM-06 Metagen19VM-20 Metagen19VM-21
# TR1 TR2 local
  gather_facts: no
  tasks:
#   - name: Install Python Pip
#     apt: pkg=python-pip state=installed update_cache=true

#   - name: Install Python modules to support Docker
#     apt: pkg=python-docker state=installed update_cache=true

   - name: Install Docker python as a pre-requirement
     pip:
       name: docker-py
#       version: 1.7.0

#   - name: Install Docker compose as a pre-requirement
#     pip:
#       name: docker-compose
#       version: 1.7.0

#   - name: Create container storage folder
#     file:
#      path: /home/training/galaxy_storage 
#      mode: 0777
#      owner: training
#      state: directory

#   - name: Stop container
#     docker:
#       name: galaxy-workflow4metabolomics
#       image: workflow4metabolomics/galaxy-workflow4metabolomics
#       state: stopped
#     ignore_errors: yes

#   - name: Pull Docker container
#     shell: docker pull ebitraining/metagenomics:mgnify
#     become: true
#     become_user: training

#   - name: start Docker container
#     shell: docker run -it -d --rm -v /tmp/.X11-unix:/tmp/.X11-unix:rw --privileged -e DISPLAY=unix$DISPLY -v /usr/lib/nvidia-340:/usr/lib/nvidia-340 -v /usr/lib32/nvidia-340:/usr/lib32/nvidia-340 -v $HOME/data:/data/:rw --device /dev/dri --privileged --name mgnify ebitraining/metagenomics:mgnify
#     shell: docker run -t -p 8080:80 -p 8021:21 -p 8022:22 -v ~/galaxy_storage/:/export/ workflow4metabolomics/galaxy-workflow4metabolomics
#     become: true
#     become_user: training

#   - name: Pull Docker container
#     docker:
#       name: galaxy-workflow4metabolomics
#       image: workflow4metabolomics/galaxy-workflow4metabolomics
#       state: reloaded
#       devices:
#       volumes:
#       - "/home/training/galaxy_storage/:/export/:rw"
#       pull: always
#       ports:
#       - "8080:80"
#       - "8021:21"
#       - "8022:22"
#     register: Log

#   - name: Collecting  logs
#     debug: var=Log

#   - name: Pull Docker container
#     docker:
#       name: dims-workflow-galaxy-training
#       image: quay.io/computational-metabolomics/dims-workflow-galaxy-training
#       state: reloaded
#       devices:
#       - "/dev/sda:rwm"
#       pull: always
#       ports:
#       - "8080:80"

#   - name: Pull Docker container
#     docker:
#       name: ebi-embocourse2018
#       image: rsamantha/ebi-embocourse2018
#       state: reloaded
#       devices:
#       - "/dev/sda:rwm"
#       pull: always
#       ports:
#       - "8787:8787"

     #shell: docker pull rjmw/galaxy-dims-workflow-training

#   - name: Docker remove old image
#     shell: docker rmi -f 60300faf0ef8    
