---
- name: Run shell commands as they are
  become: yes
  become_method: sudo
  gather_facts: no
  hosts: MathModtopVM-31
#TR1 TR2
  tasks:
    - name: Update the software cache
      apt: update_cache=yes

    - name: make sure aptitude is installed
      apt: pkg=aptitude state=present

    - name: Upgrade all software
      apt: upgrade=yes

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: Reboot the system to apply updates
      reboot:
        msg: System reboot inititated by Ansible
        reboot_timeout: 120

    - name: Get the NVIDIA driver installer
      copy:
        #src: /media/penelopeprime/.Admin/Nvidia/NVIDIA-GRID-vSphere-6.7-440.87-443.05/NVIDIA-Linux-x86_64-440.87-grid.run
        #dest: /usr/local/NVIDIA-Linux-x86_64-440.87-grid.run
        src: /media/penelopeprime/.Admin/Nvidia/NVIDIA-GRID-vSphere-6.7-450.55-450.51.05-451.48/NVIDIA-Linux-x86_64-450.51.05-grid.run
        dest: /usr/local/NVIDIA-Linux-x86_64-450.51.05-grid.run
        owner: setup
        mode: 0777
        remote_src: True

    - name: Stop X server to install nvidia driver
      shell: |
        systemctl stop lightdm
        systemctl stop gdm3

    - name: Install NVIDIA GRID driver
      shell: /usr/local/NVIDIA-Linux-x86_64-450.51.05-grid.run -q -a -n -X -s -Z
      #shell: /usr/local/NVIDIA-Linux-x86_64-440.87-grid.run -q -a -n -X -s -Z
      # -Z
      ignore_errors: yes

    - name: Enable Nvidia Grid template file to be used for licence server config
      copy:
        src: /etc/nvidia/gridd.conf.template
        dest: /etc/nvidia/gridd.conf
        owner: root
        mode: 0611
        remote_src: True

    - name: Add NVIDIA GRID License server IP
      lineinfile: dest=/etc/nvidia/gridd.conf regexp='^ServerAddress=' line='ServerAddress=10.33.32.19'

    - name: Add NVIDIA GRID License server port
      lineinfile: dest=/etc/nvidia/gridd.conf regexp='^ServerPort=' line='ServerPort=7070'

    - name: Add NVIDIA GRID License feature
      lineinfile: dest=/etc/nvidia/gridd.conf regexp='^FeatureType=0' line='FeatureType=2'

    - name: Add NVIDIA GRID License GUI
      lineinfile: dest=/etc/nvidia/gridd.conf regexp='^#EnableUI=TRUE' line='EnableUI=TRUE'

    - name: Stop nvidia-gridd service
      service:
        name: nvidia-gridd
        state: stopped

    - name: Remove NVIDIA driver installer file
      file:
        path: /usr/local/NVIDIA-Linux-x86_64-450.51.05-grid.run
        #path: /usr/local/NVIDIA-Linux-x86_64-440.87-grid.run
        state: absent
      ignore_errors: yes

    - name: Reboot the VMs to enable the NVIDIA GRID driver
      reboot:
        msg: System reboot inititated by Ansible
        reboot_timeout: 120

    - name: Remove old Horizon agent
      shell: /usr/lib/vmware/viewagent/bin/uninstall_viewagent.sh

    - name: Reboot the VMs to apply the Horizon Agent settings
      reboot:
        msg: System reboot inititated by Ansible
        reboot_timeout: 120

    - name: Install and register the Horizon ViewAgent with the Connection server
      shell: cd /home/setup/VMware-*-linux* && ./install_viewagent.sh -r no -A yes -n "{{inventory_hostname}}" -b "{{ brokerip }}" -d "{{ vmdomain }}" -u "{{ brokeruser }}" -p "{{ brokerpass }}"
      register: HorizonInstallLog

    - name: Collecting installation logs
      debug: var=HorizonInstallLog.stdout_lines

    - name: Changing the default network in the Viewagenet configuration file
      lineinfile: dest=/etc/vmware/viewagent-custom.conf regexp='^#Subnet=192.168.1.0/24' line='Subnet=10.33.36.0/22'

    - name: Disabling Keyboard Layout Syncronisation
      lineinfile: dest=/etc/vmware/viewagent-custom.conf regexp='^#KeyboardLayoutSync=FALSE' line='KeyboardLayoutSync=TRUE'

    - name: Enable bi-directional Clipboard option between client and agent
      lineinfile: dest=/etc/vmware/config regexp='^#Clipboard.Direction=1' line='Clipboard.Direction=1'

    - name: Reboot the VMs to apply the Horizon Agent settings
      reboot:
        msg: System reboot inititated by Ansible
        reboot_timeout: 120
