---
- name: Make software sheck and update 
  hosts: triv_serv
#triv_serv local
  gather_facts: no
  tasks:
   - name: Update the software cache
     apt: update_cache=yes

   - name: Upgrade all software
     apt: upgrade=yes

   - name: Remove useless packages from the cache
     apt: 
       autoclean: yes

   - name: Remove dependencies that are no longer required
     apt: 
       autoremove: yes

   - name: check if a reboot is required
     shell: "[ -f /var/run/reboot-required ]"
     failed_when: False
     register: reboot_required
     changed_when: reboot_required.rc == 0
     notify: reboot

  handlers:
   - name: reboot
     command: shutdown -r now "Ansible reboot triggred after update"
     async: 0
     poll: 0
     ignore_errors: true
