---
- name: Restart machines after update
  hosts: TR2
  gather_facts: no
  tasks:
   - name: check if a reboot is required
     shell: "[ -f /var/run/reboot-required ]"
     failed_when: False
     register: reboot_required
     changed_when: reboot_required.rc == 0
     notify: reboot

  handlers:
   - name: restart machine after Reboot
     command: shutdown -r now "Ansible reboot triggred after update"
     async: 0
     poll: 0
     ignore_errors: true
