---
- name: Make software sheck and update
  hosts: TR1
#TR1 TR2 local
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
   - name: Update the software cache
     apt: update_cache=yes

   - name: make sure aptitude is installed
     apt: pkg=aptitude state=present

   - name: Upgrade all software
     apt: upgrade=yes

   - name: Remove useless packages from the cache
     apt:
       autoclean: yes

   - name: Remove dependencies that are no longer required
     apt:
       autoremove: yes

   - name: check if a reboot is required
     shell: "[ -f /var/run/reboot-required ]"
     failed_when: False
     register: reboot_required
     changed_when: reboot_required.rc == 0
#     notify: reboot

  handlers:
   - name: reboot
     command: shutdown -r 1 "Ansible reboot triggred after update"
     async: 0
     poll: 0
     ignore_errors: true
