---
- name : Windows Update Register stopper
  hosts: spare
#ThinClientTR1 ThinClientTR2
  gather_facts: no
  tasks:
#    - name: Making sure that all Windows update services are stopped
#      win_service:
#        name: wuauserv
#        start_mode: manual
#        state: stopped

#    - win_service:
#       name: bits
#       start_mode: manual
#       state: stopped

    - name: Disable auto update registery 
#      raw: Set-ItemProperty -Path "HKLM:SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU" -Name NoAutoUpdate -Value 1
      win_shell: Get-Content servers.txt | New-RegKey -Key "SOFTWARE\Policies\Microsoft\Windows" -Name "WindowsUpdate\AU" -PassThru | Set-RegString -Value NoAutoUpdate -Data 1 -Force -PassThru

