---
- name: Install packages into Windows
  hosts: ThinClientTR1
  gather_facts: no
  tasks:
#    - name: Copy Installation file to the shared space
#      win_copy: src=/media/penelopeprime/AtomSetup.msi dest=c:\SWSETUP\


  - name: Ensure silverlight installed
    win_chocolatey:
      name: silverlight
      state: present
      version: 5.1.50907.0
      source: http://internal/odata/repo


#    - name: Execute an msi file
#      win_msi:
#        path: C:\\SWSETUP\AtomSetup.msi
#        wait: true

#    - name: Executing the installation steps
#      raw: C:\\SWSETUP\AtomSetup.msi #wait=true

#    - name: Remove Installation filde from the shared space
#      win_file: path=C:\\SWSETUP\AtomSetup.msi state=absent
