---
- name: Uninstalls Windows hotfixes and updates
  hosts: r1spare
#ThinClientTR1 ThinClientTR2
  gather_facts: no
  tasks:
#    - name: Copy PSWindowsUpdate module folder
#      win_copy:
#        src: /media/penelopeprime/Archive/PSWindowsUpdate
#        dest: 'C:\Windows\System32\WindowsPowerShell\v1.0\Modules\'
#        force: yes

    - name: Enable execution policy for the PSWindowsUpdate Module
      raw: Start-Process powershell -verb RunAs -ArgumentList 'Set-ExecutionPolicy Unrestricted -Force'

#    - name: Enable PSWindowsUpdate Module
#      raw: Import-Module PSWindowsUpdate 

    - name: Add a powershell module
      win_psmodule:
        name: PSWindowsUpdate
        state: present
      ignore_errors: yes

    - name: Start Windows Update service
      win_service:
        name: wuauserv
        start_mode: delayed
        state: started
      ignore_errors: yes

    - name: Check for missing updates
      win_updates:
        state: searched
      register: update_count
      ignore_errors: yes

    - name: remove unwanted update
      win_shell: Get-WUUninstall –KBArticleID 'KB4088786' -Confirm:$false
      register: unistall-log
      ignore_errors: yes

    - win_reboot:
      when: unistall-log.reboot_required

#    - name: Hide unwanted update
#      win_shell: Hide-WindowsUpdate –KBArticleID 'KB4088786' -Confirm:$false
#      register: update_hiding
#      ignore_errors: yes

#    - debug: var=update_hiding

    - name: Uninstall broken update with Identifier
      win_hotfix:
        hotfix_identifier: 'Package_for_RollupFix~31bf3856ad364e35~amd64~~10240.17797.1.6'
        state: absent
      register: hotfix_uninstall
      ignore_errors: yes

    - win_reboot:
      when: hotfix_uninstall.reboot_required

#    - name: Uninstall update with KB (not recommended)
#      win_hotfix:
#        hotfix_kb: KB4088786
#        state: absent
#      register: hotfix_uninstall
#      ignore_errors: yes

#    - win_reboot:
#      when: hotfix_uninstall.reboot_required 

#    - name: Start Windows Update service
#      win_service:
#        name: wuauserv
#        start_mode: delayed
#        state: started
#      ignore_errors: yes

#    - name: Check for missing updates
#      win_updates:
#        state: searched
#      register: update_count
#      ignore_errors: yes

#    - name: Add a powershell module
#      win_psmodule:
#        name: PSWindowsUpdate
#        state: present
#      ignore_errors: yes

#    - name: Hide unwanted update
#      win_shell: Hide-WindowsUpdate -Title "2018-03 Cumulative Update for Windows 10 Version 1507*" -Confirm:$false
#      raw: Hide-WUUpdate –KBArticleID 'KB4088786' –Confirm:$false
#      register: update_hiding
#      ignore_errors: yes
  
#    - debug: var=update_hiding
    
#    - raw: Remove-Item 'C:\Windows\System32\WindowsPowerShell\v1.0\Modules\PSWindowsUpdate\._*' 

#   dism /online /remove-package /packagename:Package_for_KB

#   HIde_WUUpdate -KBArticleID KBXXXXX
