---
- name : Ansible Playbook to patch and update Windows hosts
  hosts: ThinClientTR1 ThinClientTR2
#ThinClientTR1 ThinClientTR2
#  serial: 1
  gather_facts: no 
  tasks:
    # Make sure the Windows Update service is started
    - name: Start Windows Update service
      win_service:
        name: wuauserv
        start_mode: delayed
        state: started
      ignore_errors: yes

    # Check if there are missing updates
    - block:
        - name: Check for missing updates
          win_updates: 
            state: searched
          register: update_count
          ignore_errors: yes

        - name: Add a powershell module
          win_psmodule:
            name: PSWindowsUpdate
            state: present
          ignore_errors: yes

        - name: Hide unwanted update
          raw: Hide-WUUpdate –KBArticleID 'KB4088786' –Confirm:$false
          register: update_hiding
          ignore_errors: yes

    - debug: var=update_hiding.stdout_lines
 
      #Install missing updates only if at least one is missing
    - block:
        - name: Install missing updates
          win_updates:
            category_names:
              - SecurityUpdates
              - Connectors
              - SecurityUpdates
              - CriticalUpdates
              - UpdateRollups
              - DefinitionUpdates
              - FeaturePacks
              - Application
              - ServicePacks
              - Tools
              - Updates
              - DeveloperKits
              - Guidance
          ignore_errors: yes
          register: update_result
        - name: Reboot, if needed
          win_reboot:
            msg: Reboot initiated by Ansible
          when: update_result.reboot_required
          ignore_errors: yes
        - name: Reboot, if Failed 
          win_reboot:
            msg: Reboot initiated by Ansible
          when: update_result.failed
          ignore_errors: yes
      when: update_count.found_update_count|int >= 1

 
    - name: Restart all Machines
      win_reboot:
        msg: Reboot initiated by Ansible after Windows update
        pre_reboot_delay_sec: 10
