---
- name: Close a currently running application in Windows hosts
  hosts: ThinClientTR2 ThinClientTR1
#ThinClientTR2 ThinClientTR1
  gather_facts: no
  tasks:
    - name: Stop the running process gracefully
      raw: Stop-Process -processname vmware-view -force
#      raw: Stop-Process -processname WINWORD -force
      register: output

    - debug: var=output

