---
- name: Update Windows softwares using Chocolatey
  hosts: ThinClientTR2 r1u20 r1u22 r1u18
#ThinClientTR1 ThinClientTR2 
  gather_facts: no
  tasks:
    - name: set the cache location
      win_chocolatey_config:
        name: cacheLocation
        state: present
        value: C:\Temp

    - name: Ensure nice-dcv-client installed
      win_shell: choco install nice-dcv-client --version=2019.1.7114

    - name: Install Chocolatey
      win_chocolatey:
        name: '{{ item }}'
        state: latest
      with_items:
        - chocolatey
        - chocolatey-core.extension
        - powershell
      ignore_errors: yes

    - name: set the cache location
      win_chocolatey_config:
        name: cacheLocation
        state: present
        value: C:\Temp

#    - name: Stop the running process gracefully
#      raw: Stop-Process -processname vmware-view -force

#    - name: Uninstall VMware Horizon
#      win_chocolatey:
#        name: vmware-horizon-client
#        state: absent
#      ignore_errors: yes

    - name: Install VMware Horizon
      win_chocolatey:
        name: vmware-horizon-client
        state: latest
#        version: '5.0.0'
#        force: yes
      ignore_errors: yes

    - name: Install and update web browsers
      win_chocolatey:
        name: '{{ item }}'
        state: latest
      with_items:
        - firefox
        - googlechrome
        - silverlight
        - quicktime
      ignore_errors: yes

    - name: Install and update NotePad++
      win_chocolatey:
        name: notepadplusplus.install
        state: latest

    - name: Create a Desktop Icon for NotePad++
      win_copy: src=/Users/alibi/ansible_playbooks/Notepad++.lnk dest=C:\Users\Public\Desktop\Notepad++.lnk

    - name: Install and update archiver
      win_chocolatey:
#        name: 7zip
#        state: present
#        version: 19.0
#        source: http://internal/odata/repo
        name: 7zip.install
        state: latest

    - name: install and update Adobe tools
      win_chocolatey:
        name: '{{ item }}'
        state: latest
      async: 60
      poll: 5
      with_items:
        - flashplayerplugin
        - flashplayeractivex
        - adobeair
        - adobeshockwaveplayer
        - flashplayerppapi
        - flashplayerplugin
        - adobereader-update
 #       - adobereader
        - silverlight
      ignore_errors: yes


    - name: Ensure adobereader installed
      win_chocolatey:
        name: adobereader
        state: present
        version: 2020.006.20034
        source: http://internal/odata/repo
      ignore_errors: yes

    - name: Install and update Java JRE Plugin
      win_chocolatey:
        name: '{{ item }}'
        state: latest 
      with_items:
        - javaruntime
        - jre8
      ignore_errors: yes

    - name: Install and update OS Plugins and Tools
      win_chocolatey:
        name: '{{ item }}'
        state: latest
      async: 60
      with_items:
        - curl
        - python2
        - python
        - openssh
        - wget 
#        - atom 
        - putty
      ignore_errors: yes









#    - name: Install and update Atom
#      win_chocolatey:
#        name: atom
#        state: latest
#      async: 45
#      poll: 5
#      ignore_errors: yes



























#     - win_command: 'New-Item -ItemType SymbolicLink -Path "C:\Users\Public\Desktop\" -Name "NotePad++.lnk" -Value "C:\Progra$

#    - name: Copy the MSI file to the host
#      win_copy:
#        src=/media/penelopeprime/Scripts/Horizon_tarballs/VMware-Horizon-Client-4.6.1-6748947.exe
#        dest=C:\VMware-Horizon-Client-4.6.1-6748947.exe

#    - name: Update VMware Horizon
#      raw: Start-Process -Wait -FilePath C:\VMware-Horizon-Client-4.6.1-6748947.exe -ArgumentList '/S /V"/qn REBOOT=Reallysuppress"'

#    - name: Delete the MSI file
#      win_file: path=C:\VMware-Horizon-Client-4.6.1-6748947.exe state=absent

#    - name: Install and update the essential software
#      win_chocolatey:
#        name: 7zip firefox googlechrome notepadplusplus notepadplusplus.install javaruntime  #nscp
#        state: latest
#        upgrade: yes


#    - name: Upgrade all installed software to the lastest version 
#      win_chocolatey:
#        name: all
#        state: latest

#####    - name: Update Adobereader
#####      win_chocolatey:
#####        name: adobereader
#####        upgrade: True

#    - name: Update Browsers media and flash Plugin
#      win_chocolatey:
#        name: flashplayerplugin flashplayeractivex adobeair adobeshockwaveplayer silverlight
#        state: latest
#        force: yes
#        upgrade: yes

#        version: 1.12.5
#        source: https://github.com/atom/atom/releases/download/v1.12.5/
#        state: absent

#    - name: Install and update Atom text editor
#      win_chocolatey:
#        name: atom
#        state: latest
#        force: yes
#        upgrade: yes

#        version: 1.15.0
#        source: https://github.com/atom/atom/releases/

#    - name: Install and update Adobe PDF Reader
#      win_chocolatey:
#        name: adobereader-update
#        state: latest
#        force: yes
#        upgrade: yes
