---
- name: Stop Windows Updates
  hosts: ThinClientTR2
#ThinClientTR1 ThinClientTR2
  gather_facts: no
  tasks:
   - name: Make sure that the WindowsUpdate key is on the registry
     win_regedit:
       path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
       state: present
     ignore_errors: yes

   - name: Add register to disable AutoUpdate
     win_regedit:
       path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
       name: NoAutoUpdate
       data: 1
       type: dword
     ignore_errors: yes

   - name: Add register to notify for download and notify for install
     win_regedit:
       path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
       name: AUOptions
       data: 2
       type: dword
     ignore_errors: yes

   - name: Stop the Windows Update service
     win_service:
       name: wuauserv
       start_mode: disabled
       state: stopped


#   - win_service:
#       name: bits
#       start_mode: disabled
#       state: stopped


#   - name: Disable Windows Updates 
#New-RegKey -Key "SOFTWARE\Policies\Microsoft\Windows" -Name "WindowsUpdate\AU" -PassThru | Set-RegString -Value NoAutoUpdate -Data 1 -Force -PassThru

## Option for Start_mode: 	auto		manual		disabled
##      Option for State:	started		stopped		restarted
